package sec1;

public class Exception2 {

	public static void main(String[] args) {
		int[] arr=new int[3];
		int i=0;
		while (i<=3){
			try {
				arr[i]=i*10-5;
				i++;
				System.out.println();
			} catch (Exception e) {
				// TODO: handle exception
			}
		}
		

	}

}
